name: "Upload to Cachix"

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-cache:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        nixChannel:
          - nixos-24.11 # update this when a new version is available
          - nixos-unstable
          - nixpkgs-unstable
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Install Nix
      uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/refs/heads/${{ matrix.nixChannel }}.tar.gz
        
    - name: Set version
      run: |
        echo "current ref ${{ github.ref }}"
        cargo run -p edit_version -- ${{ github.ref }}
    
    - name: Setup Cachix
      uses: cachix/cachix-action@v12
      with:
        name: emmylua-analyzer
        authToken: '${{ secrets.CACHIX }}'
        
    - name: Build and cache dependencies
      run: |
        nix build .#emmylua_{ls,doc_cli,check}
